seed: 42

data:
  test_size: 0.2
  val_size: 0.2

model:
  type: lightgbm
  max_depth: 6
  learning_rate: 0.05
  n_estimators: 500
  early_stopping_rounds: 50

mlflow:
  experiment_name: adult-income
  tracking_uri: http://127.0.0.1:8082